### ISSUE TITLE
Admin->Subject Mapping->Edit Subjects.

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#114]
This action button is to activate or deactivate subject so there should be an option of activation and deactivation in the popup as other forms have such options.
![2021-01-11 15_29_57-Window.png](https://images.zenhubusercontent.com/5fe045a08d2c76c95e0ad117/8630bbd4-e957-4e11-ac5a-6c87bd570bbe)

**Comment by mluqmanbabar124** [comment]
solved..
field added
![image](https://user-images.githubusercontent.com/68840838/104173875-2e786800-5428-11eb-9083-10ada96f0c00.png)
