### ISSUE TITLE
Lecture Time

### ISSUE THREAD

**Issue by gitfabintel** [Qasim-Rafi/AppSPA#22]
Time table is not saving  and correct Spelling from Leacture to "Lecture"
![TimeTable.png](https://images.zenhubusercontent.com/5fd72b09b937e6376e682023/8f008bb1-ca7b-4e8a-9410-7e9cfe919b72)

**Comment by mluqmanbabar124** [comment]
![image](https://user-images.githubusercontent.com/68840838/102210303-ce0f0d00-3ef3-11eb-9c3f-6924f64e4291.png)
