### ISSUE TITLE
No form validations on Roll#, date of birth, country, state and password on ADD NEW USER FORM.

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#32]
1:Same roll# can be assigned to different students. 
2:Future date can be selected as Date of birth.
3:Form can be submitted without entering country and state.
4:Password with less than 6 characters is being accepted.

![2020-12-24 12_02_36-Window.png](https://images.zenhubusercontent.com/5fe045a08d2c76c95e0ad117/1798a22d-8c79-4ee1-8617-2b43d8fa06e8)

**Comment by mluqmanbabar124** [comment]
resolved..
![image](https://user-images.githubusercontent.com/68840838/103081584-0bf9e880-45fa-11eb-865f-f82dfc42f2ea.png)

**Comment by xani595** [comment]
Still no validation on roll# and date of birth.
