### ISSUE TITLE
Wrong counting is getting displayed on home page (employees, parents, events)

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#34]
![2020-12-24 12_11_42-Window.png](https://images.zenhubusercontent.com/5fe045a08d2c76c95e0ad117/1efdd8c4-bb8d-48b3-b93c-0910deae9b6a)

**Comment by mluqmanbabar124** [comment]
Events are fine now..
![image](https://user-images.githubusercontent.com/68840838/104153387-10007580-5404-11eb-861e-915a705587b4.png)
