### ISSUE TITLE
Correct number of events are not being displayed on home page. Also calender shows the month of latest saved event rather than showing the current date and month.

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#48]
![2020-12-24 12_51_07-Window.png](https://images.zenhubusercontent.com/5fe045a08d2c76c95e0ad117/e07a6493-c1fd-4a8e-9a14-a7d53331483b)

**Comment by mluqmanbabar124** [comment]
solved

**Comment by xani595** [comment]
Issue of number of events is solved but calendar is still not showing current month, is that the scenario?
