### ISSUE TITLE
On changing user type from teacher to student, roll number option is not getting displayed.

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#70]
![2020-12-29 17_25_13-Window.png](https://images.zenhubusercontent.com/5fe045a08d2c76c95e0ad117/477c3231-033a-4749-82c7-dbe8e967ecef)

**Comment by mluqmanbabar124** [comment]
roll no is Auto generated..Now

**Comment by xani595** [comment]
Then this textbox (roll no) shouldn't be there.

![2021-01-04 11_32_57-Window](https://user-images.githubusercontent.com/54904570/103507286-a242cf80-4e80-11eb-9ea3-03c61502fac7.png)
