### ISSUE TITLE
Event Managemment.

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#76]
Adding more than required characters in event title doesn't give any response (no error message or any other response which tells user that he/she is entering wrong input)

![2020-12-30 11_40_34-Window.png](https://images.zenhubusercontent.com/5fe045a08d2c76c95e0ad117/3874be54-93db-4d2d-a9e8-93d4a3843fa4)

**Comment by mluqmanbabar124** [comment]
solved..
max length is applied
![image](https://user-images.githubusercontent.com/68840838/104004842-143f4f80-51c6-11eb-9bfd-19139308c6eb.png)
