### ISSUE TITLE
Events Management

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#77]
On adding large number of characters as event title, event tag shows no text. As event management will display the notices announced on the notice board as well, when user will add any announcement containing more details it will cause a problem.

![2020-12-30 11_48_46-Window](https://user-images.githubusercontent.com/54904570/103334923-1c481280-4a95-11eb-8418-d0253a4e118c.png)

**Comment by mluqmanbabar124** [comment]
you have to select the color of event default is white

**Comment by mluqmanbabar124** [comment]
make a bug if u want to set default color other then white
