### ISSUE TITLE
Subject mapping

### ISSUE THREAD

**Issue by xani595** [Qasim-Rafi/AppSPA#96]
On deleting any subject from the list it still gets displayed in the list.
I deleted physics in that case but it is still on the list.
![Screenshot (549).png](https://images.zenhubusercontent.com/5fe045a08d2c76c95e0ad117/b090a388-889a-437a-b735-c0e0ff86b519)

**Comment by Ijaz-Tufail** [comment]
to do from front end

**Comment by mluqmanbabar124** [comment]
solved..

**Comment by xani595** [comment]
Not solved on my side yet.
